In [4]:
import numpy as np

# Question 1:

In [8]:
np.arange(2,50,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

# Question 2:

In [13]:
lst1 = [1, 7, 0, 6, 2, 5, 6]
lst2 = [4, 6, 2, 3, 1, 5, 7]
arr1 = numpy.array(lst1)
arr2 = numpy.array(lst2)
print(arr1)
print(arr2)

[1 7 0 6 2 5 6]
[4 6 2 3 1 5 7]


In [15]:
arr3 = np.concatenate((arr1, arr2))
print(arr3)

[1 7 0 6 2 5 6 4 6 2 3 1 5 7]


In [16]:
print(np.sort(arr3))

[0 1 1 2 2 3 4 5 5 6 6 6 7 7]


# Question 3:

In [17]:
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)

In [18]:
type(x)

numpy.ndarray

In [19]:
x.shape

(2, 3)

In [20]:
print(x.ndim)

2


# Question 4:

In [24]:
arr1 = np.array([1, 2, 3, 4])
print(arr1)

[1 2 3 4]


In [25]:
arr2 = np.reshape(a_1d_array, (-1, 2))
print(arr2)

[[1 2]
 [3 4]]


# Question 5:

In [32]:
a1 = np.array([[1, 2], [3, 4]])
a2 = np.array([[5, 6], [7, 8]])

print(np.hstack((a1, a2)))

[[1 2 5 6]
 [3 4 7 8]]


In [33]:
print(np.vstack((a1, a2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Question 6:

In [38]:
lst1 = [1, 1, 2, 2, 3]
arr1 = numpy.array(lst1)
unique = np.unique(arr1)
print(unique)

[1 2 3]


In [40]:
print(len(unique))

3
